### ISSUE TITLE
Publication tracking issue

### ISSUE THREAD

**Issue by daemontus** [jcrozum/biobalm#55]
This is a "tracking issue" for everything that needs to be completed in order to (hopefully) have a nice paper about `nfvs-motifs` in the end. I'll try to gradually create smaller issues for things that are not blocked by other tasks. Please use this issue for "high level" comments about paper structure and goals. I'll probably forget to add some things, so if you see that something is missing, feel free to edit my post and add it (github should let you do it as repo admins).

 > We might need to alter the structure to accommodate journal constraints (e.g. move some of this to the supplement). But until we have the actual submission guidelines, I propose the following high level structure.
 - Introduction
    - This can probably be written last once we have all the results. Hence I am not creating any issues for it yet. But if you have some ideas about what you definitely want to have here, feel free to make notes in overleaf.
 - Theory
    - I see this as a place to introduce all "common" concepts that we will rely on throughout the paper. Not all papers have this, but it'll probably be very useful for us.
    - [x] I think it is safe to say that we'll need to at least define what is a Boolean network, attractor, trap space, percolation and stable motif (#56).
    - [x] We need to define a locally-monotonic Boolean function, signed influence graph of a BN, negative cycle and negative feedback vertex set (#57).
    - [x] #68
    - [ ] We need to define the random models for Boolean networks that we are interested in. That is: (a) degree distribution (constant vs. exponential) (b) function distribution (random vs. monotonic (or threshold/canalising)) (#58).
 - Methods
    - So far, this is incomplete because some of the aspects of the algorithm are up for debate. Hence I'm only trying to describe the minimal viable points so far.
    - [ ] Define succession diagrams and "partial" succession diagrams with stub nodes (#59).
    - [ ] Describe how a basic "partial" succession diagram is constructed using `trappist`/ASP.
    - [ ] Describe how the diagram can be further expanded to aid with attractor search (separate candidate states from NFVS into different trap spaces).
    - [ ] Describe how the diagram can be further expanded to aid with control (largest trap spaces in the strong basin of the target attractor).
    - [ ] Other technical aspects of attractor search (simulation, static analysis, exhaustive symbolic search, ...).
    - [ ] Other technical aspects of control.
    - [ ] Describe what real-world networks are considered (BBM) and how we generate random networks (we'll probably need something at least semi-custom).
 - Results
    - [ ] Check how common are threshold/canalising functions in actual real-world networks in order to justify their use in the random networks (we might not need this if we chose a different generator of random networks) (#65).
    - [ ] Proof/counter-example that "interval" update allows motif-avoidant attractors (#63).
    - [x] Proof/counter-example that locally-monotonic functions allow motif-avoidant attractors (#64).
    - [ ] Compute attractors for the "matrix" of considered options (real world/random constant/random exponential/random monotonic) (#60, #61).
    - [ ] Benchmark attractor detection compared to other methods.
 - Discussion
    - Again, it does not make sense to write this until we have the results, but the high-level plan is to answer the following questions:
      - [ ] Are there *any* trap-avoidant attractors in real-world networks?      
      - [ ] How different are attractors from their enclosing minimal trap spaces? (this may not be that interesting, but relates to the previous question)
      - [ ] Are there trap-avoidant attractors in "interval" networks? If yes, are they different from the "generalised" networks? (Overall, we should end up with a hierarchy of update concurrency and attractors vs. trap spaces)
      - [ ] Are there trap-avoidant attractors in locally-monotonic networks? If yes, are they significantly different from "normal" networks?
      - [ ] Is there a difference in attractor scaling between constant and exponential in-degree distributions?
      - [ ] What is the scaling of succession diagram height? (log(n) and sqrt(n) seem like good candidates)
      - [ ] Is our method faster than other methods? (it should be :D)

Right now, I haven't given any contributions/experiments regarding control. I'll think about what we can add in this regard. Some kind of benchmark is definitely possible, but something more "biological" would be nice too...

**Comment by daemontus** [comment]
The paper is done. Let's close this.
